### PR TITLE
add fonts file to support utf encoded characters

### PR DESCRIPTION
**Pull request by wush978**
After testing closely, I notice that we do not need to change the locale setting. Installing fonts should be enough for #5 .

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks good to me.

**Comment by wch** [comment]
I'm not sure that it makes sense to add this font package to the image, since it's just one of many languages that could be added. It's probably a better idea to leave the image as-is and let users create their own images based on it, with whatever font they need.

@wush978 is the problem that Chinese characters don't show up in the web page in general, or that they don't show up in graphics like plots?

**Comment by eddelbuettel** [comment]
@wch Good point re inflation of images.  Maybe we should think of shiny as "shiny-base".

**Comment by wush978** [comment]
@wch: they don't show up in graphics.

I agree with the point of @wch, but I want to address that it is not easy to resolve such issue. In my experience, it is hard to google the solution directly.

**Comment by wch** [comment]
Perhaps a good solution is to have a wiki page about using non-latin fonts in R graphics.

**Comment by wush978** [comment]
Because installing font package is a necessary step to deploy application in a specific language with `shiny`, I prefer hosting multiple shiny image for different languages.

No matter you want to rename the image to `shiny-base` as @eddelbuettel suggseted or not, I could help you to maintain the `shiny-traditional-chinese`. If you do not want to host images for different languages, I could host it by myself.

Could I close this PR? We can keep discussing this issue in #5 .

**Pull request closed without merging**
