### PR TITLE
Bug fix: Shiny doesn't work with non-ascii files

### PR DESCRIPTION
**Pull request by MatthieuBizien**
Example :

Error in source(file, ..., keep.source = TRUE, encoding = checkEncoding(file)) :
  /srv/shiny-server/server.R:21:28: unexpected INCOMPLETE_STRING
20:                                    icon = icon("bar-chart")),
21:                   menuItem("xxx
                               ^

Where   /srv/shiny-server/server.R:21:28 is xxxé

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Nice catch -- this looks useful, and un-intrusive.   Any thoughts,  @wch and @cboettig ?

**Comment by wch** [comment]
Looks reasonable to me. @eddelbuettel, @cboettig it's possible that `LANG` should also be set for the base R docker image.

**Comment by cboettig** [comment]
:+1: for setting LANG in the base image (I've recently started setting LANG in the rstudio image as well).

**Comment by wch** [comment]
@cboettig Just curious - why did you start setting it in the RStudio image?

**Comment by cboettig** [comment]
@wch Because it solved this issue: https://github.com/rstudio/rmarkdown/issues/383 (which has subsequently also been solved in pre-release rstudio)

**Comment by eddelbuettel** [comment]
And done in 0f65030c5b2e09a329d3690ee4a295e8ef016d49

**Comment by MatthieuBizien** [comment]
:thumbsup:

**Pull request merged**
